name = "photography-blog-backend"
main = "functions/worker.js"
compatibility_date = "2023-12-01"
node_compat = true

[env.production]
account_id = dccc66c0370169ebcc732b5f40c2af1c

# Environment variables will be set in the Cloudflare dashboard
[vars]
NODE_ENV = "production" 