name = "photography-blog-backend"
main = "functions/worker.js"
compatibility_date = "2025-12-24"
compatibility_flags = [ "nodejs_compat", "enable_nodejs_http_server_modules" ]


minify = true

[vars]
NODE_ENV = "production"